### ISSUE TITLE
The logo node is fully transparent and it freezes the Comfy UI canvas

### ISSUE THREAD

**Issue by JorgeR81** [aegis72/aegisflow_utility_nodes#6]
The logo node has been fully transparent for a while. No logo is shown.

But now, it also makes the Comfy UI canvas to freeze, with the new Comfy UI frontend.

![logo0](https://github.com/user-attachments/assets/3015d26c-db6f-49f2-9d5e-dbfea38959be)

---

If you can't fix this right now, can you at least disable the logo node? 
It's the first one on my search box, and sometimes I add it by accident.

![logo](https://github.com/user-attachments/assets/6c738e8d-44ff-47dc-bbd5-007d3bc2ba70)

**Comment by PGCRT** [comment]
Same issue
